services:
   artur_ze_alves_moses.moses:
       class: ArturZeAlves\MosesBundle\Moses
       arguments: ["@artur_ze_alves_moses.writer.default"]

   artur_ze_alves_moses.writer.default:
       class: ArturZeAlves\MosesBundle\Writer\DefaultWriter
    #    arguments: ["@service_id", "plain_value", "%parameter%"]
